# Generated by Django 4.1.5 on 2023-01-18 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_currency'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Currency',
        ),
    ]
