# Generated by Django 4.1.5 on 2023-01-18 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_delete_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
