# Generated by Django 4.1.5 on 2023-01-27 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='commentable',
            field=models.BooleanField(default=True),
        ),
    ]
